### ISSUE TITLE
List inventories

### ISSUE THREAD

**Issue by ZongyangYue** [CSCI-GA-2820-FA24-003/inventory#1]
**As an** Inventory Manager
**I need** the ability to list all inventories 
**So that** I can view and manage the restock levels and the condition of the item (e.g. new, open box, used)
   
 ### Details and Assumptions
 * Inventory will be stored in a PostgreSQL Database
 * An Inventory has a name, product_id, quantity, restock_level, and item_condition
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given there are multiple items in the inventory database
 When I request to list all inventories through a query similar to "SELECT * FROM inventory"
 Then I should see a list of all items and their name, product_id, quantity, restock_level, and item conditions
```

**Comment by egnechng** [comment]
We could make this more specific. We can query for a certain item in the inventory using the product_id as the key.

**Comment by king0ffire** [comment]
> We could make this more specific. We can query for a certain item in the inventory using the product_id as the key.

#17
