### ISSUE TITLE
Secondary Database to store deleted inventory items

### ISSUE THREAD

**Issue by RayChen666** [CSCI-GA-2820-FA24-003/inventory#13]
**As a** inventory manager
**I need** a secondary database to store deleted inventory items  
**So that** deleted items can be put back or permanently deleted 
   
 ### Details and Assumptions
 * function button to put back deleted inventory items to its original database
 * function button to permanently delete an inventory item
 * search functionality by inventory ID
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given user logged in to deleted inventory item database (the secondary database)
 When user click "put back", the deleted inventory item should be put back to its original place and be removed from the secondary database;     
 When user click "delete permanently", the deleted inventory item will be deleted permanently and cannot be found anyway.
```

**Comment by egnechng** [comment]
This can be implemented using another Database model with new properties
