### ISSUE TITLE
Logging status of inventory system

### ISSUE THREAD

**Issue by king0ffire** [CSCI-GA-2820-FA24-003/inventory#14]
**As a** developer in scrum team
**I need** a function that can track and log the status of the Inventory System 
**So that** I could better understand what the system is doing
   
 ### Details and Assumptions
 * Python has a logging module, and we can make use of it.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a running Inventory System
 When a CRUD API is called
 Then log the console output, indicating what happened and whether the request succeeded.
```

**Comment by egnechng** [comment]
I think we should be more specific on the title. For example, "Logging status inventory system"
