### ISSUE TITLE
Read inventory Item

### ISSUE THREAD

**Issue by egnechng** [CSCI-GA-2820-FA24-003/inventory#17]
As an inventory manager,
I need the ability to view details of an existing inventory item using its product_id,
So that I can efficiently review and track inventory items.

## Details and Assumptions
- The inventory item details will be retrieved from the PostgreSQL database.
- The inventory item details will include name, product_id, quantity, restock_level, and item_condition values.

## Acceptance Criteria
Given the user is logged in as an inventory manager,
When the user requests to view an inventory item by providing a valid product_id,
Then the inventory item details should be retrieved from the API and displayed with all of the corresponding values from the database.

**Comment by king0ffire** [comment]
It would be like, give a id or name, and then the api tells me everything we know about that single item

**Comment by egnechng** [comment]
We will use an SKU for the product_id, correct?
