### ISSUE TITLE
Need a database model for inventory

### ISSUE THREAD

**Issue by ZongyangYue** [CSCI-GA-2820-FA24-003/inventory#3]
**As a** developer
**I need** a place to persist inventory information
**So that** inventory information can be accessed from different sessions.
   
 ### Details and Assumptions
 * Need to decide what database to use and create a data model
 * An inventory item will have a name, product_id, quantity, restock_level and item_condition value associated with it
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a new piece of inventory information
 When I want to save the information
 Then I have a database to store it.
```

**Comment by egnechng** [comment]
We are using PostgreSQL database
