### ISSUE TITLE
Need to deploy to local Kubernetes cluster

### ISSUE THREAD

**Issue by king0ffire** [CSCI-GA-2820-FA24-003/inventory#38]
**As a** developer
**I need** to deploy the inventory system and PostgreSQL database to a Kubernetes cluster
**So that** the system can persist data and be tested in a containerized environment  
   
 ### Details and Assumptions
 * Need a ./k8s folder with manifest files for deployment (deployment.yaml, service.yaml, ingress.yaml, etc.) so that Kubernetes will know how to deploy your application.

   
 ### Acceptance Criteria  
   
 ```gherkin
Given the inventory repo,
When a developer `make cluster` and apply all manifest in k8s folder 
Then the application and PostgreSQL database are successfully deployed to the cluster.
```

**Comment by egnechng** [comment]
This will cover requirement 3

**Comment by egnechng** [comment]
Need to do:
- Set up local Kubernetes cluster
- Add 'make cluster' command to Makefile
- configure proper yaml files for k8s and postgres directories
- deploy database as a StatefulSet, and change the database name to 'inventory'
- Add \health endpoint
- Deploy service to local kubernetes cluster, make sure it works, ensure ingress can access application
- Update README to contain information on running local cluster
