### ISSUE TITLE
Need a technical debt label

### ISSUE THREAD

**Issue by ZongyangYue** [CSCI-GA-2820-FA24-003/inventory#4]
**As a** developer
**I need** the ability to label a story with a technical debt tag
**So that** I can better classify stories
   
 ### Details and Assumptions
 * Using ZenHub and GitHub issues as the Kanban board
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a few stories on the Kanban board
 When I want to label a story as technical debt
 Then I should have this label popped up in the list of Labels in yellow color
```

**Comment by king0ffire** [comment]
I have added the "technical debt" label.
I believe I have successfully completed this issue, but further reviews would be necessary to ensure that everyone can view, use, and understand it.
