### ISSUE TITLE
Need a Start Process for Restocking 

### ISSUE THREAD

**Issue by king0ffire** [CSCI-GA-2820-FA24-003/inventory#44]
**As a** inventory manager
**I need** an endpoint for starting the process of restocking
**So that**  inventory items that are being restocked will not be restocked twice
   
 ### Details and Assumptions
 * Requirement 1
 * A new attribute for the restocking status needs to be added to the model.
 * An Action is a method that does something to the resource other than CRUD. Some actions might be cancelling an order, liking a product or recommendation, suspending a customer, etc. Refer to the lecture of REST API's for more examples of Action
 
 ### Acceptance Criteria  
   
 ```gherkin
 Given an inventory item ID
 When the inventory manager decides to restock it
 Then the system will label it as "restocking" and return a JSON response indicating success
```

**Comment by egnechng** [comment]
I think for this, if we update the inventory by calling the update endpoint. And if that takes the value under the restock_level value, then we automatically trigger a restock. This can be automatic ordering of items or just alerting the system that the inventory manager must put in a new order for more stock.
